[package]
name = "gtcogs"
version = "0.1.0"
authors = ["Tomas Gavenciak <gavento@ucw.cz>", "Neal Powell <pashneal@gmail.com>"]
edition = "2021"

[dependencies]
bit-set = "0.5"
rand = "0.6"
hashbrown = "0.1"
serde_json = "1.0"
regex = "1.10.2"
dashmap = "5.5.3"

[profile.release]
debug = true
